encoding: utf-8
gems:
  - jekyll-sitemap
redcarpet:
  extensions: [
    fenced_code_blocks,
    no_intra_emphasis,
    autolink,
    tables,
    with_toc_data
  ]
highlighter: pygments
exclude: [ contributing.md, tutorial/, rake_lib/, tutorials/ ]
